Description: maheshdb RDS

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: maheshdb
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2

  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: maheshdb
      EC2VpcId: !ImportValue VPC
      DBSecurityGroupIngress:
        - CIDRIP: 124.158.17.130/32
        - CIDRIP: 10.0.0.0/8
        - CIDRIP: 172.16.0.0/12

  RDS: 
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: maheshdb
      Engine: MySQL
      MasterUsername: root
      MasterUserPassword: a1b2c3d4e5
      DBSecurityGroups:
      - !Ref DBSecurityGroup
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      EngineVersion: 5.6.40
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup

Outputs:
  DBInstanceIdentifier:
    Value: !Ref RDS
    Export:
      Name: maheshdbDBInstanceIdentifier

  InternalDNS:
    Value: !GetAtt RDS.Endpoint.Address
    Export:
      Name: maheshdbInternalDNS

  Port:
    Value: !GetAtt RDS.Endpoint.Port
    Export:
      Name: maheshdbPort

